name = "instantgrow-create-checkout"
main = "index.ts"
compatibility_date = "2024-03-01"

[vars]
ALLOWED_ORIGIN = "https://instantgrow.net"
PB_URL = "https://pb.instantgrow.net"

# Secret variables should be configured via Wrangler CLI:
# wrangler secret put STRIPE_SECRET_KEY
# wrangler secret put PB_ADMIN_EMAIL
# wrangler secret put PB_ADMIN_PASSWORD
