-- Seed data: Programmatic SEO country pages
insert into public.countries_seo_pages (slug, country_name, country_code, meta_title, meta_description, hero_title, hero_description, main_keyword, secondary_keywords, pain_points, benefits, best_bank, bank_notes, tax_notes, faq_json, cta_text, published) values
(
  'egypt',
  'Egypt',
  'EG',
  'US LLC Formation for Egyptian Entrepreneurs | Instant Grow',
  'Complete guide to forming a US LLC from Egypt. Learn about banking options, US-Egypt tax treaties, compliance, and how to run your US company remotely from Cairo or anywhere in Egypt.',
  'Form Your US LLC from Egypt',
  'Launch your US company from Egypt with zero US presence required. Open a US bank account remotely, benefit from the US-Egypt tax treaty, and accept payments globally — all while living in Egypt.',
  'US LLC Egypt',
  array['LLC for Egyptians', 'US company from Egypt', 'Egyptian entrepreneurs US LLC', 'US bank account Egypt'],
  '["Confusing US incorporation process from Egypt", "High US banking minimums for non-residents", "Unclear US-Egypt tax obligations", "Limited payment processing options for Egyptian founders"]',
  '[{"title": "Zero US Presence Required", "desc": "Form your LLC completely online from Egypt. No US visa, address, or residency needed."}, {"title": "Remote US Bank Account", "desc": "Open a Mercury or Relay bank account from Egypt without visiting the US. Receive a US routing number."}, {"title": "US-Egypt Tax Treaty Benefits", "desc": "Leverage the tax treaty between the US and Egypt to avoid double taxation on your business income."}, {"title": "Global Payment Processing", "desc": "Accept payments via Stripe, PayPal, and other US-based processors unavailable to Egyptian residents."}]',
  'Mercury',
  'Mercury is the top choice for Egyptian founders — no minimum balance, no monthly fees, remote verification with Egyptian passport.',
  'Egypt has a tax treaty with the US. LLC profits are generally not taxed in Egypt unless remitted. Consult a local tax advisor for your specific situation.',
  '[{"question": "Can an Egyptian citizen form a US LLC?", "answer": "Yes, absolutely. US LLC formation does not require US citizenship or residency. You can form one entirely online from Egypt using a registered agent service."}, {"question": "Do I need a US visa to form an LLC?", "answer": "No, you do not need any US visa or physical presence. The entire process can be completed remotely from Egypt."}, {"question": "Which US state is best for Egyptian founders?", "answer": "Wyoming and Delaware are the most popular choices. Wyoming has lower annual fees and no state income tax, while Delaware has a well-established legal system."}, {"question": "Can I open a US bank account from Egypt?", "answer": "Yes, online banks like Mercury and Relay allow Egyptian founders to open accounts remotely with their Egyptian passport and LLC documents."}, {"question": "How are LLC profits taxed in Egypt?", "answer": "Under the US-Egypt tax treaty, LLC profits may be exempt from Egyptian taxation if the business has no permanent establishment in Egypt. However, consult a tax professional for your specific case."}, {"question": "How much does it cost to form a US LLC from Egypt?", "answer": "The total cost ranges from $300-$800 depending on the state and registered agent. Instant Grow offers LLC formation starting at $297."}]',
  'Start Your US LLC from Egypt',
  true
),
(
  'saudi-arabia',
  'Saudi Arabia',
  'SA',
  'US LLC Formation for Saudi Entrepreneurs | Instant Grow',
  'Complete guide to forming a US LLC from Saudi Arabia. Learn about banking, US-Saudi tax considerations, compliance, and running your US company from Riyadh or Jeddah.',
  'Form Your US LLC from Saudi Arabia',
  'Launch your US company from Saudi Arabia without leaving the Kingdom. Open a US bank account remotely, navigate US-Saudi tax rules, and scale globally.',
  'US LLC Saudi Arabia',
  array['LLC for Saudis', 'US company from Saudi Arabia', 'Saudi entrepreneurs US LLC', 'US bank account Saudi Arabia'],
  '["Complex US company registration for Saudi nationals", "Limited US banking access from Saudi Arabia", "Uncertain tax implications under Saudi law", "Difficulty accepting international payments as Saudi resident"]',
  '[{"title": "100% Remote Formation", "desc": "Form your LLC entirely online from Saudi Arabia. No US travel, visa, or in-person requirements."}, {"title": "US Bank Account from KSA", "desc": "Open a US bank account remotely. Mercury and Relay support Saudi passports and proof of address."}, {"title": "Saudi Tax Compliance", "desc": "Understand how your US LLC interacts with Zakat, VAT, and Saudi income tax regulations."}, {"title": "Access US Payment Gateways", "desc": "Accept payments through Stripe, PayPal, and other US processors to serve global clients."}]',
  'Mercury',
  'Mercury works well for Saudi founders. Use your Saudi passport for identity verification. Relay is a good alternative.',
  'Saudi Arabia does not have a formal income tax treaty with the US. LLC income may be subject to Zakat or other Saudi taxes. Always consult a Saudi tax advisor.',
  '[{"question": "Can a Saudi national form a US LLC?", "answer": "Yes, Saudi nationals can form a US LLC entirely online. No US residency or citizenship is required."}, {"question": "What US bank can I use from Saudi Arabia?", "answer": "Mercury and Relay are the most accessible. Both support remote onboarding with a Saudi passport and LLC formation documents."}, {"question": "Does Saudi Arabia tax US LLC income?", "answer": "Saudi tax treatment depends on your residency status and business activities. Consult a Saudi tax advisor, especially regarding Zakat obligations."}, {"question": "Which US state is best?", "answer": "Wyoming is popular for Saudi founders due to no state income tax and strong privacy protections."}, {"question": "Can I use Saudi ID documents for verification?", "answer": "Yes, your Saudi passport is sufficient for US LLC formation and most online bank verifications."}]',
  'Start Your US LLC from Saudi Arabia',
  true
),
(
  'uae',
  'United Arab Emirates',
  'AE',
  'US LLC Formation for UAE Entrepreneurs | Instant Grow',
  'Complete guide to forming a US LLC from the UAE. Learn about banking, US-UAE tax treaty benefits, free zone considerations, and running your US company from Dubai or Abu Dhabi.',
  'Form Your US LLC from the UAE',
  'Launch your US company from Dubai, Abu Dhabi, or anywhere in the UAE. Leverage the US-UAE tax treaty, open a US bank account remotely, and grow your global business.',
  'US LLC UAE',
  array['LLC for UAE residents', 'US company from Dubai', 'UAE entrepreneurs US LLC', 'Dubai US LLC formation'],
  '["Confusing US vs UAE company structure options", "Banking hurdles for UAE residents opening US accounts", "Understanding US-UAE tax treaty application", "Choosing between Dubai free zone and US LLC"]',
  '[{"title": "Seamless Remote Formation", "desc": "Form your LLC online from Dubai or Abu Dhabi. No US presence or travel needed."}, {"title": "US-UAE Tax Treaty Advantage", "desc": "The US-UAE tax treaty provides strong protection against double taxation for UAE residents."}, {"title": "Remote US Banking", "desc": "Open Mercury or Relay accounts from the UAE using your Emirates ID or passport."}, {"title": "Free Zone vs LLC Clarity", "desc": "Understand when a US LLC makes more sense than a Dubai free zone company for your business."}]',
  'Mercury',
  'Mercury is the top choice for UAE founders. They accept UAE residency proof and passports. Wise multi-currency accounts also pair well.',
  'The US-UAE tax treaty generally prevents double taxation. LLC income is typically not taxed in the UAE (no corporate income tax for most activities).',
  '[{"question": "Can I form a US LLC while living in Dubai?", "answer": "Yes, absolutely. Many UAE entrepreneurs form US LLCs to access US payment gateways and serve American clients."}, {"question": "US LLC or Dubai Free Zone?", "answer": "A US LLC is better if your customers are primarily in the US. Free zones are better for UAE-local operations. Some entrepreneurs use both structures."}, {"question": "Can I open a US bank account from the UAE?", "answer": "Yes. Mercury and Relay both accept UAE residents. You need your LLC documents and valid passport/Emirates ID."}, {"question": "Does the UAE tax US LLC income?", "answer": "The UAE has no corporate income tax for most mainland businesses. Under the US-UAE tax treaty, LLC income should not be double-taxed."}, {"question": "What is the total cost?", "answer": "US LLC formation costs $300-$800. Instant Grow offers packages starting at $297 + state fees."}]',
  'Start Your US LLC from the UAE',
  true
),
(
  'morocco',
  'Morocco',
  'MA',
  'US LLC Formation for Moroccan Entrepreneurs | Instant Grow',
  'Complete guide to forming a US LLC from Morocco. Learn about banking, US-Morocco tax treaty benefits, compliance, and running your US company from Casablanca or Marrakech.',
  'Form Your US LLC from Morocco',
  'Launch your US company from Morocco with zero US presence. Open a US bank account remotely, benefit from the US-Morocco tax treaty, and access global payments.',
  'US LLC Morocco',
  array['LLC for Moroccans', 'US company from Morocco', 'Moroccan entrepreneurs US LLC', 'US bank account Morocco'],
  '["Limited US banking options for Moroccan residents", "Complex US-Morocco tax compliance", "Payment processing restrictions for Moroccan businesses", "Language barriers in legal processes"]',
  '[{"title": "Fully Remote Formation", "desc": "Form your LLC online from Morocco. French and Arabic support available through our platform."}, {"title": "US Bank Account from Morocco", "desc": "Open a Mercury or Relay bank account remotely using your Moroccan passport."}, {"title": "US-Morocco Tax Treaty", "desc": "The US-Morocco tax treaty helps avoid double taxation on your LLC income."}, {"title": "Global Payment Access", "desc": "Accept payments via US-based processors like Stripe to serve international clients."}]',
  'Mercury',
  'Mercury supports Moroccan residents. Use your passport for verification. Wise is a good alternative for multi-currency needs.',
  'Morocco has a tax treaty with the US. LLC income is generally taxable only in the US unless you have a permanent establishment in Morocco. Consult a Moroccan tax expert.',
  '[{"question": "Can a Moroccan citizen form a US LLC?", "answer": "Yes, Moroccan citizens can form a US LLC entirely online. The process does not require US residency or citizenship."}, {"question": "What bank can I use from Morocco?", "answer": "Mercury is the most accessible for Moroccan founders. Wise Business also works well for multi-currency accounts."}, {"question": "How does the US-Morocco tax treaty affect my LLC?", "answer": "Under the treaty, business profits are generally taxed only in the US unless you have a permanent establishment in Morocco. This can significantly reduce your tax burden."}, {"question": "Is the process available in French or Arabic?", "answer": "Our platform supports both English and Arabic. We also provide French-language support for Moroccan clients."}, {"question": "Which US state is best?", "answer": "Wyoming is recommended for Moroccan founders — no state income tax, low annual fees, and strong privacy protections."}]',
  'Start Your US LLC from Morocco',
  true
) on conflict (slug) do nothing;

